set_value:
  fields:
    node:
      required: true
      example: 36
    attribute:
      required: true
      example: 90
    value:
      required: true
      example: 1
update_entity:
  target:
    entity:
      integration: homee